2014-02-11 14:57:02,966 DEBUG {'data_object': {}, 'auth_request': {'appKey': '816cc20437d859538736e1ef46558b7bda486c06', 'appName': 'myapp'}, 'sock': <socket._socketobject object at 0x11011a980>, 'app_key': 'mykey', 'auth_response': '', 'app_name': 'myapp'}
2014-02-11 14:57:02,967 ERROR Authorization failed!
2014-02-11 14:59:19,858 ERROR Cannot connect to socket!
2014-02-11 14:59:23,642 ERROR Cannot connect to socket!
2014-02-11 15:16:31,913 DEBUG {'data_object': {}, 'auth_request': {'appKey': '816cc20437d859538736e1ef46558b7bda486c06', 'appName': 'myapp'}, 'sock': <socket._socketobject object at 0x1095c6980>, 'app_key': 'mykey', 'auth_response': '\xaa\xaa\x02\xc8', 'app_name': 'myapp'}
2014-02-11 15:16:31,913 ERROR Authorization failed!
2014-02-11 15:20:51,718 DEBUG {'data_object': {}, 'auth_request': {'appKey': '816cc20437d859538736e1ef46558b7bda486c06', 'appName': 'myapp'}, 'sock': <socket._socketobject object at 0x10a3f0980>, 'app_key': 'mykey', 'auth_response': '\xaa\xaa\x02\xc8', 'app_name': 'myapp'}
2014-02-11 15:20:51,719 ERROR Authorization failed!
2014-02-11 15:22:02,805 DEBUG {'data_object': {}, 'auth_request': {'appKey': '816cc20437d859538736e1ef46558b7bda486c06', 'appName': 'myapp'}, 'sock': <socket._socketobject object at 0x10cd6b980>, 'app_key': 'mykey', 'auth_response': '\xaa\xaa\x02\xc8', 'app_name': 'myapp'}
2014-02-11 15:22:02,805 ERROR Authorization failed!
2014-02-11 15:23:07,882 DEBUG {'data_object': {}, 'auth_request': '{"appName": "Brainwave Shooters", "appKey": "9f54141b4b4c567c558d3a76cb8d715cbde03096"}', 'sock': <socket._socketobject object at 0x10b1cd980>, 'app_key': 'mykey', 'auth_response': '\xaa\xaa\x02\xc8', 'app_name': 'myapp'}
2014-02-11 15:23:07,882 ERROR Authorization failed!
2014-02-11 15:35:12,369 INFO Connecting to TGC socket...
2014-02-11 15:35:12,369 INFO Authenticating...
2014-02-11 15:35:12,809 INFO Configuring TGC to use JSON...
2014-02-11 15:35:12,810 INFO Recording brain data...
2014-02-11 15:58:57,548 INFO Connecting to TGC socket...
2014-02-11 15:58:57,549 INFO Authenticating...
2014-02-11 15:58:57,549 ERROR Cannot connect to socket!
2014-02-11 16:14:42,928 INFO Connecting to TGC socket...
2014-02-11 16:14:42,928 INFO Authenticating...
2014-02-11 16:14:42,928 ERROR Cannot connect to socket!
2014-02-11 16:15:11,562 INFO Connecting to TGC socket...
2014-02-11 16:15:11,563 INFO Authenticating...
2014-02-11 16:15:11,563 ERROR Cannot connect to socket!
2014-02-11 16:15:35,728 INFO Connecting to TGC socket...
2014-02-11 16:15:35,728 INFO Authenticating...
2014-02-11 16:15:35,728 ERROR Cannot connect to socket!
2014-02-11 16:19:33,757 INFO Connecting to TGC socket...
2014-02-11 16:19:33,757 INFO Authenticating...
2014-02-11 16:19:33,757 ERROR Cannot connect to socket!
2014-02-11 16:19:55,018 INFO Connecting to TGC socket...
2014-02-11 16:19:55,018 INFO Authenticating...
2014-02-11 16:19:55,019 ERROR Cannot connect to socket!
2014-02-11 16:20:01,107 INFO Connecting to TGC socket...
2014-02-11 16:20:01,107 INFO Authenticating...
2014-02-11 16:20:01,108 ERROR Cannot connect to socket!
2014-02-11 22:06:45,964 INFO Connecting to TGC socket...
2014-02-11 22:06:45,965 INFO Authenticating...
2014-02-11 22:06:45,965 ERROR Cannot connect to socket!
2014-02-11 22:07:08,369 INFO Connecting to TGC socket...
2014-02-11 22:07:08,369 INFO Authenticating...
2014-02-11 22:07:08,369 ERROR Cannot connect to socket!
2014-02-11 22:09:31,949 INFO Connecting to TGC socket...
2014-02-11 22:09:31,949 INFO Authenticating...
2014-02-11 22:09:31,949 ERROR Cannot connect to socket!
2014-02-11 22:24:37,043 INFO Connecting to TGC socket...
2014-02-11 22:24:37,062 INFO Authenticating...
2014-02-11 22:24:37,062 ERROR Cannot connect to socket!
2014-02-11 23:18:53,132 INFO Connecting to TGC socket...
2014-02-11 23:18:53,133 INFO Authenticating...
2014-02-11 23:18:53,133 ERROR <type 'exceptions.Exception'>
2014-02-11 23:18:53,133 ERROR Cannot connect to socket!
2014-02-11 23:19:26,236 INFO Connecting to TGC socket...
2014-02-11 23:19:26,237 INFO Authenticating...
2014-02-11 23:19:26,237 ERROR <type 'exceptions.Exception'>
2014-02-11 23:19:26,237 ERROR Cannot connect to socket!
2014-02-11 23:23:34,553 INFO Connecting to TGC socket...
2014-02-11 23:23:34,554 INFO Connected.
2014-02-11 23:23:34,554 INFO Authenticating...
2014-02-11 23:23:34,554 ERROR Exception:
Traceback (most recent call last):
  File "./medit8.py", line 58, in <module>
    if(conn.authenticate(APPNAME, APPKEY)):
  File "./medit8.py", line 35, in authenticate
    self.app_key = hashlib.sha1(self.app_key).hexdigest()
AttributeError: ThinkGearConnection instance has no attribute 'app_key'
2014-02-11 23:23:34,555 ERROR No connection with TGC socket
2014-02-11 23:24:48,396 INFO Connecting to TGC socket...
2014-02-11 23:24:48,397 INFO Connected.
2014-02-11 23:24:48,401 INFO Authenticating...
2014-02-11 23:24:48,401 INFO Authenticate string: {"appKey": "da39a3ee5e6b4b0d3255bfef95601890afd80709", "appName": "myapp"}
2014-02-11 23:24:49,028 INFO Configuring TGC to use JSON...
2014-02-11 23:24:49,028 INFO Recording brain data...
2014-02-11 23:27:37,340 INFO Connecting to TGC socket...
2014-02-11 23:27:37,340 INFO Connected.
2014-02-11 23:27:37,341 INFO Authenticating...
2014-02-11 23:27:37,341 INFO Authenticate string: {"appKey": "da39a3ee5e6b4b0d3255bfef95601890afd80709", "appName": "myapp"}
2014-02-11 23:27:37,863 INFO Configuring TGC to use JSON...
2014-02-11 23:27:37,864 INFO Recording brain data...
2014-02-13 16:50:26,196 INFO Connecting to TGC socket...
2014-02-13 16:50:26,196 INFO Connected.
2014-02-13 16:50:26,197 INFO Authenticating...
2014-02-13 16:50:26,197 INFO Authenticate string: {"appKey": "da39a3ee5e6b4b0d3255bfef95601890afd80709", "appName": "myapp"}
2014-02-13 16:50:26,440 INFO Configuring TGC to use JSON...
2014-02-13 16:50:26,440 INFO Recording brain data...
2014-02-13 16:50:26,440 ERROR Exception:
Traceback (most recent call last):
  File "./medit8.py", line 71, in <module>
    conn.record_data()
  File "./medit8.py", line 52, in record_data
    f = open(STATFILE,"w")
NameError: global name 'STATFILE' is not defined
2014-02-13 16:50:26,441 ERROR No connection with TGC socket
2014-02-13 16:51:35,437 INFO Connecting to TGC socket...
2014-02-13 16:51:35,437 INFO Connected.
2014-02-13 16:51:35,437 INFO Authenticating...
2014-02-13 16:51:35,438 INFO Authenticate string: {"appKey": "da39a3ee5e6b4b0d3255bfef95601890afd80709", "appName": "myapp"}
2014-02-13 16:51:35,545 INFO Configuring TGC to use JSON...
2014-02-13 16:51:35,545 INFO Recording brain data...
2014-02-13 16:51:36,045 ERROR Exception:
Traceback (most recent call last):
  File "./medit8.py", line 71, in <module>
    conn.record_data()
  File "./medit8.py", line 56, in record_data
    self.data = json.loads(self.data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 383, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
2014-02-13 16:51:36,047 ERROR No connection with TGC socket
2014-02-13 16:52:11,647 INFO Connecting to TGC socket...
2014-02-13 16:52:11,647 INFO Connected.
2014-02-13 16:52:11,647 INFO Authenticating...
2014-02-13 16:52:11,647 INFO Authenticate string: {"appKey": "da39a3ee5e6b4b0d3255bfef95601890afd80709", "appName": "myapp"}
2014-02-13 16:52:12,094 INFO Configuring TGC to use JSON...
2014-02-13 16:52:12,094 INFO Recording brain data...
2014-02-13 16:54:11,832 INFO Connecting to TGC socket...
2014-02-13 16:54:11,833 INFO Connected.
2014-02-13 16:54:11,833 INFO Authenticating...
2014-02-13 16:54:11,833 INFO Authenticate string: {"appKey": "da39a3ee5e6b4b0d3255bfef95601890afd80709", "appName": "myapp"}
2014-02-13 16:54:12,272 INFO Configuring TGC to use JSON...
2014-02-13 16:54:12,272 INFO Recording brain data...
2014-02-13 16:59:29,967 INFO Connecting to TGC socket...
2014-02-13 16:59:29,968 INFO Connected.
2014-02-13 16:59:29,968 INFO Authenticating...
2014-02-13 16:59:29,968 INFO Authenticate string: {"appKey": "da39a3ee5e6b4b0d3255bfef95601890afd80709", "appName": "myapp"}
2014-02-13 16:59:30,204 INFO Configuring TGC to use JSON...
2014-02-13 16:59:30,204 INFO Recording brain data...
2014-02-13 17:26:22,455 INFO Connecting to TGC socket...
2014-02-13 17:26:22,455 INFO Connected.
2014-02-13 17:26:22,456 INFO Authenticating...
2014-02-13 17:26:22,456 INFO Authenticate string: {"appKey": "da39a3ee5e6b4b0d3255bfef95601890afd80709", "appName": "myapp"}
2014-02-13 17:26:22,868 INFO Configuring TGC to use JSON...
2014-02-13 17:26:22,869 INFO Recording brain data...
2014-02-13 17:26:23,370 ERROR Exception:
Traceback (most recent call last):
  File "./medit8.py", line 101, in <module>
    conn.record_data()
  File "./medit8.py", line 74, in record_data
    self.data_to_write.extend(self.json_data['poorSignalLevel'])
AttributeError: ThinkGearConnection instance has no attribute 'data_to_write'
2014-02-13 17:26:23,370 ERROR No connection with TGC socket
2014-02-13 17:26:54,974 INFO Connecting to TGC socket...
2014-02-13 17:26:54,975 INFO Connected.
2014-02-13 17:26:54,975 INFO Authenticating...
2014-02-13 17:26:54,975 INFO Authenticate string: {"appKey": "da39a3ee5e6b4b0d3255bfef95601890afd80709", "appName": "myapp"}
2014-02-13 17:26:55,411 INFO Configuring TGC to use JSON...
2014-02-13 17:26:55,411 INFO Recording brain data...
2014-02-13 17:26:55,911 ERROR Exception:
Traceback (most recent call last):
  File "./medit8.py", line 102, in <module>
    conn.record_data()
  File "./medit8.py", line 75, in record_data
    self.data_to_write.extend(self.json_data['poorSignalLevel'])
TypeError: 'int' object is not iterable
2014-02-13 17:26:55,912 ERROR No connection with TGC socket
2014-02-13 17:27:47,397 INFO Connecting to TGC socket...
2014-02-13 17:27:47,397 INFO Connected.
2014-02-13 17:27:47,397 INFO Authenticating...
2014-02-13 17:27:47,398 INFO Authenticate string: {"appKey": "da39a3ee5e6b4b0d3255bfef95601890afd80709", "appName": "myapp"}
2014-02-13 17:27:47,984 INFO Configuring TGC to use JSON...
2014-02-13 17:27:47,984 INFO Recording brain data...
2014-02-13 17:27:48,485 ERROR Exception:
Traceback (most recent call last):
  File "./medit8.py", line 102, in <module>
    conn.record_data()
  File "./medit8.py", line 76, in record_data
    self.data_to_write.extend(self.json_data['attention'])
KeyError: 'attention'
2014-02-13 17:27:48,486 ERROR No connection with TGC socket
2014-02-13 17:30:22,673 INFO Connecting to TGC socket...
2014-02-13 17:30:22,673 INFO Connected.
2014-02-13 17:30:22,673 INFO Authenticating...
2014-02-13 17:30:22,674 INFO Authenticate string: {"appKey": "da39a3ee5e6b4b0d3255bfef95601890afd80709", "appName": "myapp"}
2014-02-13 17:30:23,184 INFO Configuring TGC to use JSON...
2014-02-13 17:30:23,184 INFO Recording brain data...
2014-02-13 17:30:23,685 ERROR Exception:
Traceback (most recent call last):
  File "./medit8.py", line 105, in <module>
    conn.record_data()
  File "./medit8.py", line 77, in record_data
    if (self.json_data['attention']):
KeyError: 'attention'
2014-02-13 17:30:23,685 ERROR No connection with TGC socket
2014-02-13 17:40:07,746 INFO Connecting to TGC socket...
2014-02-13 17:40:07,747 INFO Connected.
2014-02-13 17:40:07,747 INFO Authenticating...
2014-02-13 17:40:07,747 INFO Authenticate string: {"appKey": "da39a3ee5e6b4b0d3255bfef95601890afd80709", "appName": "myapp"}
2014-02-13 17:40:07,974 INFO Configuring TGC to use JSON...
2014-02-13 17:40:07,974 INFO Recording brain data...
2014-02-13 17:40:08,476 ERROR Exception:
Traceback (most recent call last):
  File "./medit8.py", line 96, in <module>
    conn.record_data()
  File "./medit8.py", line 78, in record_data
    if (self.json_data['attention']):
KeyError: 'attention'
2014-02-13 17:40:08,476 ERROR No connection with TGC socket
2014-02-13 17:40:28,482 INFO Connecting to TGC socket...
2014-02-13 17:40:28,483 INFO Connected.
2014-02-13 17:40:28,483 INFO Authenticating...
2014-02-13 17:40:28,483 INFO Authenticate string: {"appKey": "da39a3ee5e6b4b0d3255bfef95601890afd80709", "appName": "myapp"}
2014-02-13 17:40:29,003 INFO Configuring TGC to use JSON...
2014-02-13 17:40:29,003 INFO Recording brain data...
2014-02-13 17:41:59,017 INFO Connecting to TGC socket...
2014-02-13 17:41:59,017 INFO Connected.
2014-02-13 17:41:59,017 INFO Authenticating...
2014-02-13 17:41:59,017 INFO Authenticate string: {"appKey": "da39a3ee5e6b4b0d3255bfef95601890afd80709", "appName": "myapp"}
2014-02-13 17:41:59,621 INFO Configuring TGC to use JSON...
2014-02-13 17:41:59,621 INFO Recording brain data...
2014-02-13 17:42:38,020 INFO Connecting to TGC socket...
2014-02-13 17:42:38,020 INFO Connected.
2014-02-13 17:42:38,020 INFO Authenticating...
2014-02-13 17:42:38,020 INFO Authenticate string: {"appKey": "da39a3ee5e6b4b0d3255bfef95601890afd80709", "appName": "myapp"}
2014-02-13 17:42:38,186 INFO Configuring TGC to use JSON...
2014-02-13 17:42:38,186 INFO Recording brain data...
2014-02-13 17:43:04,441 INFO Connecting to TGC socket...
2014-02-13 17:43:04,441 INFO Connected.
2014-02-13 17:43:04,441 INFO Authenticating...
2014-02-13 17:43:04,441 INFO Authenticate string: {"appKey": "da39a3ee5e6b4b0d3255bfef95601890afd80709", "appName": "myapp"}
2014-02-13 17:43:04,721 INFO Configuring TGC to use JSON...
2014-02-13 17:43:04,721 INFO Recording brain data...
2014-02-13 17:43:05,222 ERROR Exception:
Traceback (most recent call last):
  File "./medit8.py", line 96, in <module>
    conn.record_data()
  File "./medit8.py", line 74, in record_data
    self.json_data = json.loads(str(self.data))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 383, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
2014-02-13 17:43:05,223 ERROR No connection with TGC socket
2014-02-13 17:43:13,906 INFO Connecting to TGC socket...
2014-02-13 17:43:13,907 INFO Connected.
2014-02-13 17:43:13,907 INFO Authenticating...
2014-02-13 17:43:13,907 INFO Authenticate string: {"appKey": "da39a3ee5e6b4b0d3255bfef95601890afd80709", "appName": "myapp"}
2014-02-13 17:43:14,231 INFO Configuring TGC to use JSON...
2014-02-13 17:43:14,232 INFO Recording brain data...
2014-02-13 17:43:14,732 ERROR Exception:
Traceback (most recent call last):
  File "./medit8.py", line 96, in <module>
    conn.record_data()
  File "./medit8.py", line 79, in record_data
    f.write(','.join(self.data_to_write)+'\n')
TypeError: sequence item 0: expected string, int found
2014-02-13 17:43:14,732 ERROR No connection with TGC socket
2014-02-13 17:48:15,635 INFO Connecting to TGC socket...
2014-02-13 17:48:15,635 INFO Connected.
2014-02-13 17:48:15,635 INFO Authenticating...
2014-02-13 17:48:15,636 INFO Authenticate string: {"appKey": "da39a3ee5e6b4b0d3255bfef95601890afd80709", "appName": "myapp"}
2014-02-13 17:48:16,147 INFO Configuring TGC to use JSON...
2014-02-13 17:48:16,147 INFO Recording brain data...
2014-02-13 17:48:16,648 ERROR Exception:
Traceback (most recent call last):
  File "./medit8.py", line 98, in <module>
    conn.record_data()
  File "./medit8.py", line 81, in record_data
    f.write(','.join(self.data_to_write)+'\n')
TypeError: sequence item 0: expected string, int found
2014-02-13 17:48:16,648 ERROR No connection with TGC socket
2014-02-13 17:49:59,492 INFO Connecting to TGC socket...
2014-02-13 17:49:59,492 INFO Connected.
2014-02-13 17:49:59,492 INFO Authenticating...
2014-02-13 17:49:59,492 INFO Authenticate string: {"appKey": "da39a3ee5e6b4b0d3255bfef95601890afd80709", "appName": "myapp"}
2014-02-13 17:49:59,794 INFO Configuring TGC to use JSON...
2014-02-13 17:49:59,794 INFO Recording brain data...
2014-02-13 17:50:00,295 ERROR Exception:
Traceback (most recent call last):
  File "./medit8.py", line 98, in <module>
    conn.record_data()
  File "./medit8.py", line 81, in record_data
    f.write(str(','.join(self.data_to_write))+'\n')
TypeError: sequence item 0: expected string, int found
2014-02-13 17:50:00,295 ERROR No connection with TGC socket
2014-02-13 17:50:38,197 INFO Connecting to TGC socket...
2014-02-13 17:50:38,197 INFO Connected.
2014-02-13 17:50:38,197 INFO Authenticating...
2014-02-13 17:50:38,197 INFO Authenticate string: {"appKey": "da39a3ee5e6b4b0d3255bfef95601890afd80709", "appName": "myapp"}
2014-02-13 17:50:38,344 INFO Configuring TGC to use JSON...
2014-02-13 17:50:38,345 INFO Recording brain data...
2014-02-13 17:50:38,845 ERROR Exception:
Traceback (most recent call last):
  File "./medit8.py", line 99, in <module>
    conn.record_data()
  File "./medit8.py", line 82, in record_data
    print ','.join(self.data_to_write)
TypeError: sequence item 0: expected string, int found
2014-02-13 17:50:38,845 ERROR No connection with TGC socket
2014-02-13 17:50:58,912 INFO Connecting to TGC socket...
2014-02-13 17:50:58,912 INFO Connected.
2014-02-13 17:50:58,912 INFO Authenticating...
2014-02-13 17:50:58,913 INFO Authenticate string: {"appKey": "da39a3ee5e6b4b0d3255bfef95601890afd80709", "appName": "myapp"}
2014-02-13 17:50:59,370 INFO Configuring TGC to use JSON...
2014-02-13 17:50:59,371 INFO Recording brain data...
2014-02-13 17:51:29,638 INFO Connecting to TGC socket...
2014-02-13 17:51:29,638 INFO Connected.
2014-02-13 17:51:29,638 INFO Authenticating...
2014-02-13 17:51:29,638 INFO Authenticate string: {"appKey": "da39a3ee5e6b4b0d3255bfef95601890afd80709", "appName": "myapp"}
2014-02-13 17:51:29,909 INFO Configuring TGC to use JSON...
2014-02-13 17:51:29,910 INFO Recording brain data...
2014-02-13 23:08:25,903 INFO Connecting to TGC socket...
2014-02-13 23:08:25,903 INFO Connected.
2014-02-13 23:08:25,903 INFO Authenticating...
2014-02-13 23:08:25,904 INFO Authenticate string: {"appKey": "da39a3ee5e6b4b0d3255bfef95601890afd80709", "appName": "myapp"}
2014-02-13 23:08:26,429 INFO Configuring TGC to use JSON...
2014-02-13 23:08:26,429 INFO Recording brain data...
2014-02-13 23:11:48,874 INFO Connecting to TGC socket...
2014-02-13 23:11:48,874 INFO Connected.
2014-02-13 23:11:48,875 INFO Authenticating...
2014-02-13 23:11:48,875 INFO Authenticate string: {"appKey": "da39a3ee5e6b4b0d3255bfef95601890afd80709", "appName": "myapp"}
2014-02-13 23:11:49,319 INFO Configuring TGC to use JSON...
2014-02-13 23:11:49,319 INFO Recording brain data...
2014-02-13 23:14:34,436 INFO Connecting to TGC socket...
2014-02-13 23:14:34,437 INFO Connected.
2014-02-13 23:14:34,437 INFO Authenticating...
2014-02-13 23:14:34,437 INFO Authenticate string: {"appKey": "da39a3ee5e6b4b0d3255bfef95601890afd80709", "appName": "myapp"}
2014-02-13 23:14:34,638 INFO Configuring TGC to use JSON...
2014-02-13 23:14:34,638 INFO Recording brain data...
2014-02-13 23:15:54,859 INFO Connecting to TGC socket...
2014-02-13 23:15:54,859 ERROR Exception:
Traceback (most recent call last):
  File "./medit8.py", line 95, in <module>
    conn.connect(TGHOST, TGPORT)
  File "./medit8.py", line 44, in connect
    self.sock.connect((host, int(port)))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 61] Connection refused
2014-02-13 23:15:54,861 ERROR No connection with TGC socket
2014-02-13 23:15:57,130 INFO Connecting to TGC socket...
2014-02-13 23:15:57,130 ERROR Exception:
Traceback (most recent call last):
  File "./medit8.py", line 95, in <module>
    conn.connect(TGHOST, TGPORT)
  File "./medit8.py", line 44, in connect
    self.sock.connect((host, int(port)))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 61] Connection refused
2014-02-13 23:15:57,131 ERROR No connection with TGC socket
2014-02-13 23:16:37,477 INFO Connecting to TGC socket...
2014-02-13 23:16:37,477 INFO Connected.
2014-02-13 23:16:37,477 INFO Authenticating...
2014-02-13 23:16:37,478 INFO Authenticate string: {"appKey": "da39a3ee5e6b4b0d3255bfef95601890afd80709", "appName": "myapp"}
2014-02-13 23:16:38,190 INFO Configuring TGC to use JSON...
2014-02-13 23:16:38,190 INFO Recording brain data...
2014-02-13 23:17:58,961 INFO Connecting to TGC socket...
2014-02-13 23:17:58,962 INFO Connected.
2014-02-13 23:17:58,962 INFO Authenticating...
2014-02-13 23:17:58,962 INFO Authenticate string: {"appKey": "da39a3ee5e6b4b0d3255bfef95601890afd80709", "appName": "myapp"}
2014-02-13 23:17:59,336 INFO Configuring TGC to use JSON...
2014-02-13 23:17:59,336 INFO Recording brain data...
2014-02-13 23:23:04,232 INFO Connecting to TGC socket...
2014-02-13 23:23:04,233 INFO Connected.
2014-02-13 23:23:04,233 INFO Authenticating...
2014-02-13 23:23:04,233 INFO Authenticate string: {"appKey": "da39a3ee5e6b4b0d3255bfef95601890afd80709", "appName": "myapp"}
2014-02-13 23:23:04,354 INFO Configuring TGC to use JSON...
2014-02-13 23:23:04,354 INFO Recording brain data...
2014-02-13 23:23:04,855 ERROR Exception:
Traceback (most recent call last):
  File "./medit8.py", line 100, in <module>
    conn.record_data()
  File "./medit8.py", line 74, in record_data
    self.json_data = json.loads(str(self.data))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 383, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
2014-02-13 23:23:04,858 ERROR No connection with TGC socket
2014-02-13 23:23:09,950 INFO Connecting to TGC socket...
2014-02-13 23:23:09,950 INFO Connected.
2014-02-13 23:23:09,950 INFO Authenticating...
2014-02-13 23:23:09,950 INFO Authenticate string: {"appKey": "da39a3ee5e6b4b0d3255bfef95601890afd80709", "appName": "myapp"}
2014-02-13 23:23:10,363 INFO Configuring TGC to use JSON...
2014-02-13 23:23:10,363 INFO Recording brain data...
2014-02-13 23:23:10,864 ERROR Exception:
Traceback (most recent call last):
  File "./medit8.py", line 100, in <module>
    conn.record_data()
  File "./medit8.py", line 77, in record_data
    if i in self.json_data['eegPower']:
KeyError: 'eegPower'
2014-02-13 23:23:10,864 ERROR No connection with TGC socket
2014-02-13 23:23:13,447 INFO Connecting to TGC socket...
2014-02-13 23:23:13,448 INFO Connected.
2014-02-13 23:23:13,448 INFO Authenticating...
2014-02-13 23:23:13,448 INFO Authenticate string: {"appKey": "da39a3ee5e6b4b0d3255bfef95601890afd80709", "appName": "myapp"}
2014-02-13 23:23:13,869 INFO Configuring TGC to use JSON...
2014-02-13 23:23:13,869 INFO Recording brain data...
2014-02-13 23:23:14,370 ERROR Exception:
Traceback (most recent call last):
  File "./medit8.py", line 100, in <module>
    conn.record_data()
  File "./medit8.py", line 77, in record_data
    if i in self.json_data['eegPower']:
KeyError: 'eegPower'
2014-02-13 23:23:14,370 ERROR No connection with TGC socket
2014-02-13 23:23:40,991 INFO Connecting to TGC socket...
2014-02-13 23:23:40,991 INFO Connected.
2014-02-13 23:23:40,991 INFO Authenticating...
2014-02-13 23:23:40,992 INFO Authenticate string: {"appKey": "da39a3ee5e6b4b0d3255bfef95601890afd80709", "appName": "myapp"}
2014-02-13 23:23:41,412 INFO Configuring TGC to use JSON...
2014-02-13 23:23:41,412 INFO Recording brain data...
2014-02-13 23:23:41,913 ERROR Exception:
Traceback (most recent call last):
  File "./medit8.py", line 100, in <module>
    conn.record_data()
  File "./medit8.py", line 77, in record_data
    if i in self.json_data[u'eegPower']:
KeyError: u'eegPower'
2014-02-13 23:23:41,914 ERROR No connection with TGC socket
2014-02-13 23:25:10,359 INFO Connecting to TGC socket...
2014-02-13 23:25:10,359 INFO Connected.
2014-02-13 23:25:10,359 INFO Authenticating...
2014-02-13 23:25:10,360 INFO Authenticate string: {"appKey": "da39a3ee5e6b4b0d3255bfef95601890afd80709", "appName": "myapp"}
2014-02-13 23:25:10,573 INFO Configuring TGC to use JSON...
2014-02-13 23:25:10,573 INFO Recording brain data...
2014-02-13 23:25:11,074 ERROR Exception:
Traceback (most recent call last):
  File "./medit8.py", line 101, in <module>
    conn.record_data()
  File "./medit8.py", line 74, in record_data
    self.json_data = json.loads(str(self.data))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 383, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
2014-02-13 23:25:11,076 ERROR No connection with TGC socket
2014-02-13 23:25:38,925 INFO Connecting to TGC socket...
2014-02-13 23:25:38,925 INFO Connected.
2014-02-13 23:25:38,926 INFO Authenticating...
2014-02-13 23:25:38,926 INFO Authenticate string: {"appKey": "da39a3ee5e6b4b0d3255bfef95601890afd80709", "appName": "myapp"}
2014-02-13 23:25:39,615 INFO Configuring TGC to use JSON...
2014-02-13 23:25:39,615 INFO Recording brain data...
2014-02-13 23:25:52,278 ERROR Exception:
Traceback (most recent call last):
  File "./medit8.py", line 101, in <module>
    conn.record_data()
  File "./medit8.py", line 79, in record_data
    self.data_to_write.append(str(self.json_data[i]))
KeyError: 'delta'
2014-02-13 23:25:52,279 ERROR No connection with TGC socket
2014-02-13 23:28:16,069 INFO Connecting to TGC socket...
2014-02-13 23:28:16,069 INFO Connected.
2014-02-13 23:28:16,069 INFO Authenticating...
2014-02-13 23:28:16,069 INFO Authenticate string: {"appKey": "da39a3ee5e6b4b0d3255bfef95601890afd80709", "appName": "myapp"}
2014-02-13 23:28:16,390 INFO Configuring TGC to use JSON...
2014-02-13 23:28:16,390 INFO Recording brain data...
2014-02-13 23:28:29,733 ERROR Exception:
Traceback (most recent call last):
  File "./medit8.py", line 101, in <module>
    conn.record_data()
  File "./medit8.py", line 79, in record_data
    self.data_to_write.append(str(self.json_data[i]))
KeyError: 'delta'
2014-02-13 23:28:29,734 ERROR No connection with TGC socket
2014-02-13 23:30:28,218 INFO Connecting to TGC socket...
2014-02-13 23:30:28,218 INFO Connected.
2014-02-13 23:30:28,218 INFO Authenticating...
2014-02-13 23:30:28,218 INFO Authenticate string: {"appKey": "da39a3ee5e6b4b0d3255bfef95601890afd80709", "appName": "myapp"}
2014-02-13 23:30:28,631 INFO Configuring TGC to use JSON...
2014-02-13 23:30:28,631 INFO Recording brain data...
2014-02-13 23:30:43,095 ERROR Exception:
Traceback (most recent call last):
  File "./medit8.py", line 101, in <module>
    conn.record_data()
  File "./medit8.py", line 79, in record_data
    self.data_to_write.append(str(self.json_data[i]))
KeyError: u'delta'
2014-02-13 23:30:43,095 ERROR No connection with TGC socket
2014-02-13 23:31:24,723 INFO Connecting to TGC socket...
2014-02-13 23:31:24,723 INFO Connected.
2014-02-13 23:31:24,723 INFO Authenticating...
2014-02-13 23:31:24,723 INFO Authenticate string: {"appKey": "da39a3ee5e6b4b0d3255bfef95601890afd80709", "appName": "myapp"}
2014-02-13 23:31:25,222 INFO Configuring TGC to use JSON...
2014-02-13 23:31:25,222 INFO Recording brain data...
2014-02-13 23:39:08,545 INFO Connecting to TGC socket...
2014-02-13 23:39:08,545 INFO Connected.
2014-02-13 23:39:08,545 INFO Authenticating...
2014-02-13 23:39:08,545 INFO Authenticate string: {"appKey": "da39a3ee5e6b4b0d3255bfef95601890afd80709", "appName": "myapp"}
2014-02-13 23:39:09,007 INFO Configuring TGC to use JSON...
2014-02-13 23:39:09,007 INFO Recording brain data...
